name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python            # Updated to v4
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with parallel execution and generate report
      run: pytest -n auto --html=report.html --self-contained-html tests

    - name: Upload test report
      if: always() # This ensures that the report is uploaded even if tests fail
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: pytest-report
        path: report.html
